### ISSUE TITLE
点击添加博客无反应

### ISSUE THREAD

**Issue by 1458271** [Emphasia/TumblThree-zh#1]
之前看到英文版那边有一个老哥，和我的问题比较类似**@se9099**，问题为#192，复制博客后，点击添加博客没有反应，当然，一星期前我刚用过这个软件，并且很不错，感觉不像是VPN的问题，经常弹出的一条报错信息大意是这样的（我用的是英文39），队列没有加载，可能是XXX（英文不太好）下载尚未完成，出于VPN不稳定的缘故，我有时会点击停止或者暂停，甚至任务管理器，我在想是不是这些操作导致博客下载未完成，所以添加不了新的博客？之所以有这个怀疑就是我已经添加的博客还可以下载，但是就是添加不了新的博客。。。。试过很多版本都是这样，不知道大家有没有类似的问题或者解决方法。。。

**Comment by Emphasia** [comment]
下载未完成和添加新博客并没有已知的联系..
但是添加博客要查询这个博客的相关信息必须要能访问它，网络不稳定的确是会导致添加失败的。

**Comment by 1458271** [comment]
我会找一个稳定的vpn进行尝试，十分感谢您的帮助

**Comment by 1458271** [comment]
我不知道是不是tumblr更新了css或者其他导致博客添加失败。。

**Comment by Emphasia** [comment]
vpn的情况排除了？

**Comment by 1458271** [comment]
暂时还没有找到特别稳定的vpn，我现在用的这个是xx-net，浏览器访问tumblr的话是8秒左右可以打开，感觉不是这个的问题，我在想其他有没有人遇到一样的问题。。。

**Comment by Emphasia** [comment]
你设置里代理填的啥

**Comment by 1458271** [comment]
127.0.0.1   1080
之前一直是没有问题的，但是vpn开pac智能连接的话，设置里的授权界面是打不开的，后来我改成全局，授权界面成功打开，但是依旧添加不了博客。。。。

**Comment by Emphasia** [comment]
1080是X-Tunnel模块。
你添加的博客名能方便说吗？我试试看能不能重现。

**Comment by 1458271** [comment]
https://thereisnonamehere.tumblr.com/
我刚换了一个很稳定的vpn，恩。。。自己刚搭的ssr。。。还是不能添加博客

**Comment by 1458271** [comment]
index文件夹下的那些files.tumblr的文件应该是探测的结果吧，links那一栏空空如也。。。

**Comment by Emphasia** [comment]
我也试了，GAE和XTunnel都试了，都失败。我去给作者反馈一下吧。

**Comment by 1458271** [comment]
果然不是我自己的问题。。。

**Comment by Emphasia** [comment]
@1458271 你试试添加wallpaperfx.tumblr.com

**Comment by Emphasia** [comment]
没用SS试过。

**Comment by 1458271** [comment]
GAE和XTunnel可以添加吗

**Comment by Emphasia** [comment]
都不可以。
从我的各种组合尝试来看，工具里的代理设定压根没用。但以前我刚开始参加这个项目的时候是有用的。如果能找到具体哪个版本开始就好了。

**Comment by 1458271** [comment]
我这里有一个旧版的，我以前用过没问题的版本，我来测试一下

**Comment by 1458271** [comment]
emmmm，1.0.6.8版本实测，wallpaperfx.tumblr.com可以添加

**Comment by 1458271** [comment]
39的前一个版本我没有备份，但是很有可能是从那个版本开始的

**Comment by 1458271** [comment]
我现在开始测试1.0.8.27

**Comment by 1458271** [comment]
1.0.8.27可以添加

**Comment by 1458271** [comment]
测试完毕。。。36版本开始的。。。36之前的版本都正常

**Comment by Javier0731** [comment]
请问挂SS能下载吗？需要做什么设置吗？

**Comment by Emphasia** [comment]
BUG已修复：https://github.com/Emphasia/TumblThree-zh/releases/tag/v1.0.8.41

**Comment by Emphasia** [comment]
@Javier0731 ss能。把SS代理设置到IE里，然后用41版本。

**Comment by Javier0731** [comment]
请问能大致说一下怎么设置吗？IE里我看只有填写地址和端口的地方，没有填密码的地方。。。。还是说用自动配置脚本？上面那位朋友说在程序里要填写127.0.0.1/1080。。。我有点糊涂

**Comment by Emphasia** [comment]
程序里填是以前，但是有bug不能用，现在用直接调用IE的代理，程序里的填不填都没用。
至于IE里咋填，就按SS的全局代理就行。

**Comment by Emphasia** [comment]
就你平时是先用SS工具连你的SS服务器，再去浏览器或者程序里设SS工具的地址和端口，现在把这些设到IE里去，或者直接用SS工具的“全局代理”。

**Comment by Javier0731** [comment]
![image](https://user-images.githubusercontent.com/33154954/36732894-fab7350e-1c09-11e8-8e91-1e742f227e2a.png)
我现在直接开ss就能翻墙，IE在未开ss时是勾选自动检测的，开ss后就是上图情况了。。。ss一直是全局代理

**Comment by Emphasia** [comment]
就整完IE里能正常访问汤就行。

**Comment by Javier0731** [comment]
关闭自动检测，默认开启代理服务器后可以显示下载中了。。。但下载下来的图片全是空白的只有一行地址是啥情况呢？移除后，重新添加博客又无法下载了。。。
