### ISSUE TITLE
能问一下我的授权一直无法登录是什么原因

### ISSUE THREAD

**Issue by 1029880035** [Emphasia/TumblThree-zh#2]
就是授权的登录界面不出现账号框和密码框

**Comment by Emphasia** [comment]
截图更直观一点..
不过要我猜多半是因为网络问题..（设代理了吗？）

**Comment by 1029880035** [comment]
截图了，但不知道怎么上传到聊天框里，用的代理，蓝灯和seed都试过，和网页登录的差别就是没有登录框，能加你个qq吗，我的是1029880035

**Comment by Emphasia** [comment]
工具新版本的代理设置暂时无效，老版本正常。如果要用新版本的话，建议代理设全局（或者去设IE的代理为蓝灯啥的）。
图片上传直接拖进来就行，或者截完粘贴进来，或者下面有行：
> Attach files by dragging & dropping, selecting them, or pasting from the clipboard.

**Comment by Emphasia** [comment]
https://github.com/Emphasia/TumblThree-zh/issues/1#comment-368878183
