### ISSUE TITLE
Win10 挂SS开全局代理后，IE能上汤但下载器点开始无反应

### ISSUE THREAD

**Issue by Javier0731** [Emphasia/TumblThree-zh#3]
![image](https://user-images.githubusercontent.com/33154954/36791566-2dc013c0-1cd3-11e8-8f61-e5f688290dd9.png)
![image](https://user-images.githubusercontent.com/33154954/36791627-4f46444c-1cd3-11e8-9585-d8b273a3ff97.png)
![image](https://user-images.githubusercontent.com/33154954/36791663-6aa6b0a0-1cd3-11e8-9846-42de7e6a3319.png)
![image](https://user-images.githubusercontent.com/33154954/36791728-817857de-1cd3-11e8-9e15-f0c5718ff9a8.png)

**Comment by johanneszab** [comment]
I'm only guessing what your problem is, but did you actually queue the blog? It looks like the queue (right hand side, 2nd picture) is empty.

**Comment by Javier0731** [comment]
Only once time in the queue has a task working but the progress bar is still empty, and there are some almost blank pictures in the download directory with only 'download directory path' in the picture's middle.
Except this time, when I press the start button, nothing happens in the queue.

**Comment by Emphasia** [comment]
一个博客要开始下载要满足：

- 在队列中且排到它，同时队列已开始。

所以添加博客后要先把博客加入队列再开始队列。
向队列中添加是手动的。

**Comment by Javier0731** [comment]
怪不得我tumbltwo能正常用。。。那请问怎么添加到队列？手动拖入？

**Comment by Emphasia** [comment]
![36791627-4f46444c-1cd3-11e8-9585-d8b273a3ff97](https://user-images.githubusercontent.com/8478234/36884123-ae26c742-1e19-11e8-9571-7fe91a4a04f2.png)

**Comment by Javier0731** [comment]
。。。我一直是以为点开始就会自动添加到队列中，且也按照添加顺序进行下载。。。为啥不能自动添加、下完自动退出呢😂

**Comment by Javier0731** [comment]
![image](https://user-images.githubusercontent.com/33154954/36907158-d306ed36-1e72-11e8-96db-dfcbe2e1a0d9.png)
加入队列后，可以下载了，但是为什么下载下来的图片都是0kb大小的，而且内容是下图
![image](https://user-images.githubusercontent.com/33154954/36907199-fb78456c-1e72-11e8-99f4-326956f4255e.png)

**Comment by Javier0731** [comment]
![image](https://user-images.githubusercontent.com/33154954/36933391-f0068036-1f12-11e8-9d58-03f0da57723c.png)
目前挂上代理图片还是像上面回复的那样异常下载（无论设置成RAW还是1280），但视频下载正常，是否是这个参数的问题？
我看目前一些油猴脚本里一般都是直接把图片网址前缀*.media.tumblr.com替换成s3.amazonaws.com/data.tumblr.com后就能打开原图了
![image](https://user-images.githubusercontent.com/33154954/36933453-cba1079c-1f13-11e8-93ea-49a3cf6d7f69.png)

**Comment by johanneszab** [comment]
> 我看目前一些油猴脚本里一般都是直接把图片网址前缀*.media.tumblr.com替换成s3.amazonaws.com/data.tumblr.com后就能打开原图了

It's not true. There is no difference between accessing the files using either http://s3.amazonaws.com or http://data.tumblr.com, except that the SSL certificate is wrongly issued using SSL and data.tumblr.com. But thats not really an issue.

Someone already suggested [changing the host](https://github.com/johanneszab/TumblThree/issues/168), but I couldn't find a single image that is only available using the s3.amazonaws.com host, but not the data.tumblr.com host. Neither could the original poster. Thus, unless you show me a photo, there is no reason to change the code.

As for your photo download problem, I've no clue. Downloading photos works exactly the same as for videos. They even share the same code.

**Comment by Javier0731** [comment]
![image](https://user-images.githubusercontent.com/33154954/36984595-384759d8-20d0-11e8-85c2-0cde23a00e3a.png)
Actually I've reduced the number of connections at the same time. It even fails when I download pictures only.

**Comment by johanneszab** [comment]
Tested the same settings here, no issues. Must be something on your side. Antivirus?

Like I've said earlier, when you even can download the videos, the photo download is the exact same code.

**Comment by hotdogwang1** [comment]
作者，你好，升级了1.08.41解决了不能添加博客的问题，不错，我用的是蓝灯上的网，添加博客后并队列任务，下载的图片或视频都是0kb，不知道怎么回事？
![_20180320041514](https://user-images.githubusercontent.com/37556228/37619770-66e6ae3a-2bf5-11e8-896b-b544568f65b4.png)

**Comment by hotdogwang1** [comment]
![default](https://user-images.githubusercontent.com/37556228/37619913-c1f395c2-2bf5-11e8-970e-809c9c8c3508.png)

**Comment by Emphasia** [comment]
0kb的问题我好像也碰到过 但上面提出后我尝试复现却没成功 如果能找出出现这个问题的具体条件也好对症下药

**Comment by Javier0731** [comment]
其实蛮奇怪的，我用tumbltwo下载图片超快，用Tumlthree下载视频也正常，就是下图片99%会是0kb，raw下载下来0kb，1080还是0kb。。。仅有2次反复下载图片竟然有了，但速度很慢，我已经调整为1张1张图下载了。。。所以完全搞不懂什么情况，看了爬取的log发现出现0kb的图片并没有下载地址只有一长串代码，不知道你们什么情况

**Comment by johanneszab** [comment]
Could it be that this is a proxy issue? 

Since probably multiple user use the same proxy (hence the same IP address) to access media*.tumblr.com (the image host), maybe they rate limit/prohibit access to the image for this host? If downloading with TumblThree fails, can you see the images using the web browser using the same proxy at the same time? Did you try using a different proxy/host when this issue happened?

That's pretty much the only way this issue makes sense. Since crawling (getting the image urls) works, accessing the .tumblr.com network seems to work. Also sometimes downloading the videos, which are hosted on a different host (vt.tumblr.com instead of media*.tumblr.com).

I've also never seen this issue when not using a proxy.

I've tried limiting my bandwidth to 400kb/s only and downloading 70 images concurrently, that still worked (without a proxy).

**Comment by hotdogwang1** [comment]
作者，你好，出问题时候，我网页访问tumblr的网站是没有问题的，更换了一个代理软件并更换了端口，问题依旧，下载的图片或视频都是0kb。

**Comment by johanneszab** [comment]
Can someone post a proxy, how to connect there, and how you did set it up within Windows? If you don't want to post it here, you can also send it to me by email.

Then I'll try to reproduce the error within a Visual Studio debugging session. Hopefully the same happens for me. I think otherwise we'll not be able to fix this issue if not using a debugger at the same time (within Visual Studio).

**Comment by Emphasia** [comment]
@johanneszab you can try XX-Net (I'll update this comment to complete tomorrow 😂)

**Comment by hotdogwang1** [comment]
谢谢作者的及时回复，我现在用tumblone下载图片没有一点问题，想用tumblthree下载视频看来不行，考虑到下载视频不多，用火狐插件就能解决，暂时等tumblthree新版本再试试吧。

**Comment by johanneszab** [comment]
[TumblThree-v1.0.8.45-Application.zip](https://github.com/Emphasia/TumblThree-zh/files/1832303/TumblThree-v1.0.8.45-Application.zip)
[TumblThree-v1.0.8.45-Translations.zip](https://github.com/Emphasia/TumblThree-zh/files/1832304/TumblThree-v1.0.8.45-Translations.zip)

Could someone test if this fixes the 0kb issue? Thanks!

**Comment by Javier0731** [comment]
This one works，i can download picture very fast now，I will continue testing. Thank U.

**Comment by hotdogwang1** [comment]
Thank you!  it  works well。 @johanneszab

**Comment by johanneszab** [comment]
Thanks for testing and keeping the nagging. Sometimes it hard to believe error messages (from a single person), and unfortunately I had to write the proxy code somewhat blind as I couldn't really test it without being behind the great firewall myself.

@Emphasia: I guess you can close most of your issues here now. Some of them seem related.

**Comment by Emphasia** [comment]
@johanneszab Thanks.
